# Generated by Django 2.2.1 on 2019-05-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-from_date']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='order',
        ),
    ]
